# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a6b0b7f9051327360e7f73c557037228d5dc5fb790edd37dd885638364c7c834a2f1dbba35d8b392e5c6887d06604e32ff9667af4a92c76626bc45a9de423a6

test:
  secret_key_base: e27c6ca0b02ea155054b2cbad8c63a0bf241f665d7a78a94afd0432bc5bea560d7ce65dcd592bcbda93d2587963b5a23cc6c4b57cc9e5112c4110462dba3289a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
